# image_root: '../data/final_frames_5'
image_root: '../data/coinic'
ann_root: './'
coco_gt_root: './'

# set pretrained as a file path or an url
pretrained: './base.pth'

# size of vit model; base or large

vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 4
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: False
# vit_ckpt_layer: 5
# batch_size: 1
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 40  
min_length: 5
num_beams: 3
prompt: ''

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 30
# max_epoch: 1

